config/routes.rb
Rails.application.routes.draw do
  
  resources :pets
  resources :appointments
  resources :practioners
  get 'home/index'
  get 'customer/index'
  get 'customer/pets'

  devise_for :users

  root 'home#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  
  belongs_to :practioner
  belongs_to :pet
  belongs_to :customer
  
  validates :date_of_visit, presence: true, date: {on_or_after: Date.current }

  
  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! 

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    @practioners = Practioner.all
    @pets = Pet.all
    @customers = Customer.all
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointments_path, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date_of_visit, :pet_id, :customer_id, :practioner_id, :appointment_reminder, :reason_for_visit)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_visit %><br>
    <%= f.datetime_select :date_of_visit %>
  </div>
  <div class="field">
    <%= f.label :pet_id %><br>
	<%= f.select :pet_id, Pet.all.collect {|p| [ p.name, p.id ] }, :prompt => 'Select a Pet' %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.select :customer_id, Customer.all.collect {|c| [ c.name, c.id ] }, :prompt => 'Select a Customer' %>
  </div>
  <div class="field">
    Doctor<br>
    <%= f.select :practioner_id, Practioner.all.collect {|p| [ p.name, p.id ] }, :prompt => 'Select a Doctor' %>
  </div>
  <div class="field">
    <%= f.label :appointment_reminder %><br>
    <%= f.check_box :appointment_reminder %>
  </div>
  <div class="field">
    <%= f.label :reason_for_visit %><br>
    <%= f.text_area :reason_for_visit, :size=>"50X87" %>
  </div>
  <div class="actions">
	  <br>
    <%= f.submit %>
  </div>
  
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appointments</h1>

          <div class="table-responsive">
            <table class="table table-striped">
  <thead>
    <tr>
      <th>Date of visit</th>
      <th>Pet Name</th>
      <th>Customer Name</th>
	  <th>Doctor Name</th>
      <th>Appointment reminder</th>
      <th>Reason for visit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date_of_visit %></td>
        <td><%= appointment.pet.name %></td>
        <td><%= appointment.customer.name %></td>
		 <td><%= appointment.practioner.name %></td>
        <td><%= appointment.appointment_reminder %></td>
        <td><%= appointment.reason_for_visit %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of visit:</strong>
  <%= @appointment.date_of_visit %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @appointment.pet_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @appointment.customer_id %>
</p>

<p>
  <strong>Appointment reminder:</strong>
  <%= @appointment.appointment_reminder %>
</p>

<p>
  <strong>Reason for visit:</strong>
  <%= @appointment.reason_for_visit %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>