config/routes.rb
Rails.application.routes.draw do
  
  resources :pets
  resources :appointments
  resources :practioners
  get 'home/index'
  get 'customer/index'
  get 'customer/pets'

  devise_for :users

  root 'home#index'

end

app/models/practioner.rb
class Practioner < ActiveRecord::Base
  
  belongs_to :user
  has_many :appointments
  
  validates :name, presence: true, length: { maximum: 35 }
  validates :zip, length: { maximum: 5 }
  validates :years_in_practice, inclusion: { in: 1..100 }
  
end

app/controllers/practioners_controller.rb
class PractionersController < ApplicationController
  before_action :set_practioner, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! 

  # GET /practioners
  # GET /practioners.json
  def index
    @practioners = Practioner.all
  end

  # GET /practioners/1
  # GET /practioners/1.json
  def show
  end

  # GET /practioners/new
  def new
    @practioner = Practioner.new
  end

  # GET /practioners/1/edit
  def edit
  end

  # POST /practioners
  # POST /practioners.json
  def create
    @practioner = Practioner.new(practioner_params)

    respond_to do |format|
      if @practioner.save
        format.html { redirect_to @practioner, notice: 'Practioner was successfully created.' }
        format.json { render :show, status: :created, location: @practioner }
      else
        format.html { render :new }
        format.json { render json: @practioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practioners/1
  # PATCH/PUT /practioners/1.json
  def update
    respond_to do |format|
      if @practioner.update(practioner_params)
        format.html { redirect_to @practioner, notice: 'Practioner was successfully updated.' }
        format.json { render :show, status: :ok, location: @practioner }
      else
        format.html { render :edit }
        format.json { render json: @practioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practioners/1
  # DELETE /practioners/1.json
  def destroy
    @practioner.destroy
    respond_to do |format|
      format.html { redirect_to practioners_url, notice: 'Practioner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practioner
      @practioner = Practioner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practioner_params
      params.require(:practioner).permit(:name, :address, :state, :city, :zip, :school_degree_received_from, :years_in_practice)
    end
end

app/helpers/practioners_helper.rb
module PractionersHelper
end

app/views/practioners/_form.html.erb
<%= form_for(@practioner) do |f| %>
  <% if @practioner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practioner.errors.count, "error") %> prohibited this practioner from being saved:</h2>

      <ul>
      <% @practioner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :school_degree_received_from %><br>
    <%= f.text_field :school_degree_received_from %>
  </div>
  <div class="field">
    <%= f.label :years_in_practice %><br>
	<%= f.select(:years_in_practice, (1..100), :prompt => 'Select') %>
  </div>
  <div class="actions"><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/practioners/edit.html.erb
<h1>Editing Practioner</h1>

<%= render 'form' %>

<%= link_to 'Show', @practioner %> |
<%= link_to 'Back', practioners_path %>

app/views/practioners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Practioners</h1>

          <div class="table-responsive">
            <table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
	  <th>State</th>
      <th>Zip</th>
      <th>School degree received from</th>
      <th>Years in practice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @practioners.each do |practioner| %>
      <tr>
        <td><%= practioner.name %></td>
        <td><%= practioner.address %></td>
        <td><%= practioner.city %></td>
		 <td><%= practioner.state %></td>
        <td><%= practioner.zip %></td>
        <td><%= practioner.school_degree_received_from %></td>
        <td><%= practioner.years_in_practice %></td>
        <td><%= link_to 'Show', practioner %></td>
        <td><%= link_to 'Edit', edit_practioner_path(practioner) %></td>
        <td><%= link_to 'Destroy', practioner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Practioner', new_practioner_path %>

app/views/practioners/new.html.erb
<h1>New Practioner</h1>

<%= render 'form' %>

<%= link_to 'Back', practioners_path %>

app/views/practioners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @practioner.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @practioner.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @practioner.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @practioner.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @practioner.zip %>
</p>

<p>
  <strong>School degree received from:</strong>
  <%= @practioner.school_degree_received_from %>
</p>

<p>
  <strong>Years in practice:</strong>
  <%= @practioner.years_in_practice %>
</p>

<%= link_to 'Edit', edit_practioner_path(@practioner) %> |
<%= link_to 'Back', practioners_path %>