config/routes.rb
Rails.application.routes.draw do
  
  resources :pets
  resources :appointments
  resources :practioners
  get 'home/index'
  get 'customer/index'
  get 'customer/pets'

  devise_for :users

  root 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  
  has_many :pets
  has_many :appointments
  belongs_to :user
  
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  before_filter :authenticate_user! 
  
  def index
    @customer_pet_appointments = current_user.customer.pets.flat_map(&:appointments)
  end
  
  def pets
    @customer_pets = current_user.customer.pets
  end
  
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Pet Appointments</h1>

          <div class="table-responsive">
            <table class="table table-striped">
  <thead>
    <tr>
	  <th>Pet Name</th>
      <th>Date of Next Appointment</th>
	  <th>Doctor Name</th>
      <th>Reason for visit</th>
      
    </tr>
  </thead>

  <tbody>
    <% @customer_pet_appointments.each do |appointment| %>
	<% if appointment.date_of_visit >= Date.current %>
      <tr>
		<td><%= appointment.pet.name %></td>
        <td><%= appointment.date_of_visit %></td>
		 <td><%= appointment.practioner.name  %></td>
        <td><%= appointment.reason_for_visit %></td>
      </tr>
	  <% end %>
    <% end %>
  </tbody>
</table>
</div>

<br/>
<%= link_to 'My Pets', customer_pets_path %>

app/views/customer/pets.html.erb
<p id="notice"><%= notice %></p>

<h1>My Pets</h1>

          <div class="table-responsive">
            <table class="table table-striped">
  <thead>
    <tr>
	  <th>Name</th>
      <th>Type</th>
	  <th>Breed</th>
      <th>Age</th>
	  <th>Weight</th>
	  <th>Date of Last Visit</th>
      
    </tr>
  </thead>

  <tbody>
    <% @customer_pets.each do |pet| %>
      <tr>
		<td><%= pet.name %></td>
		<td><%= pet.pet_type %></td>
		 <td><%= pet.breed  %></td>
		 <td><%= pet.age  %></td>
		 <td><%= pet.weight %></td>
        <td><%= pet.date_of_last_visit %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br/>
<%= link_to 'My Pets', customer_pets_path %>